### PR TITLE
Add issue and commit templates instructing people to always tag someo…

### PR DESCRIPTION
**Pull request by sedited**
…ne to review the pr/take the issue
@benma

### CODE REVIEW

**Comment by stephaniestroka** [comment]
I'm a bit confused by this issue. Do you mean that you want to tag reviewers in the git commit message?

**Comment by benma** [comment]
No, mark them as reviewers, or tag them in the PR message/comment.

**Comment by stephaniestroka** [comment]
Then I'm unsure what to do with this issue. @TheCharlatan can you explain?

**Comment by sedited** [comment]
This just adds a standard text that will appear in this text box, when you opene either an issue, or a pull request to "@" the maintainers so (i) they definitely get a notification and (ii) there is someone responsible for the patch.

**Comment by stephaniestroka** [comment]
Oh I see. For some reason I thought that it's an issue, not a PR. Will merge (and trust you that it's fine ;-))

**Comment by stephaniestroka** [comment]
A short meta-complaint: You could have assigned a reviewer to this PR :stuck_out_tongue:

**Comment by sedited** [comment]
I did, `@benma` is the first line of the PR text body. Non-maintainers of a github repository cannot asign people to pull requests, they have to `@` them so they get a notification.

**Comment by stephaniestroka** [comment]
Ohh, I see. Sorry, didn't think about that!

**Pull request merged**
